name: ci

on:
  push:
    branches:
      - 'master'
      - 'develop'
    tags-ignore:
      - '**'

  pull_request: ~
  workflow_dispatch: ~

  pull_request_target:
    types: [labeled]

jobs:
  ci:
    name: ci
    uses: ./.github/workflows/ci-python-template.yaml
    with:
      codecov_upload: true
      notify_teams: false
      build_package_inputs: |
        self_build: false
        dependencies: |
          ecmwf/ecbuild
          ecmwf/eckit
          ecmwf/odc
        dependency_branch: develop