name: ci

on:
  push:
    branches:
      - 'master'
      - 'develop'
    tags-ignore:
      - '**'

  pull_request: ~
  workflow_dispatch: ~

  pull_request_target:
    types: [labeled]

jobs:
  ci:
    name: ci
    uses: ecmwf-actions/reusable-workflows/.github/workflows/ci-python.yml@v1
    with:
      codecov_upload: true
      notify_teams: false
      build_package_inputs: |
        self_build: false

    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdal-dev libaec-dev