name: ci

on:
  push:
    branches:
      - 'master'
      - 'develop'
    tags-ignore:
      - '**'

  pull_request: ~
  workflow_dispatch: ~

  pull_request_target:
    types: [labeled]

jobs:
  ci:
    needs: setup
    name: ci
    uses: ecmwf-actions/reusable-workflows/.github/workflows/ci-python.yml@v1
    with:
      codecov_upload: true
      notify_teams: false
      build_package_inputs: |
        self_build: false
        dependencies: |
          ecmwf/ecbuild
          ecmwf/eckit
          ecmwf/eccodes
        dependency_branch: develop
      system_dependencies: libgdal-dev libaec-dev