name: ci

on:
  # Trigger the workflow on push to master or develop, except tag creation
  push:
    branches:
      - 'master'
      - 'develop'
    tags-ignore:
      - '**'

  # Trigger the workflow on pull request
  pull_request: ~

  # Trigger the workflow manually
  workflow_dispatch: ~

  # # Trigger after public PR approved for CI
  # pull_request_target:
  #   types: [labeled]

jobs:
  # my-job:
  #   runs-on: macOS-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Install Homebrew
  #     run: |
  #       /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  #   - name: Install Software with Homebrew
  #     run: brew install eccodes
  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.9'
  #   - name: Install dependencies
  #     run: pip install -r requirements.txt
  #   - name: Run Tests
  #     run: pytest tests

  # ci:
  #   name: ci
  #   uses: ecmwf-actions/reusable-workflows/.github/workflows/ci-python.yml@v1
  #   with:
  #     codecov_upload: true
  #     # notify_teams: true
  #     build_package_inputs: |
  #       dependencies: |
  #         ecmwf/ecbuild
  #         ecmwf/eckit
  #         ecmwf/odc
  #         ecmwf/eccodes
  #       dependency_branch: develop

    ci:
    name: ci
    uses: ecmwf-actions/build-package@v2
    with:
      self_coverage: true
      force_build: true
      cache_suffix: "${{ matrix.build_type }}-${{ env.CACHE_SUFFIX }}"
      recreate_cache: ${{ matrix.caching == false }}
      # notify_teams: true
      dependencies: |
        ecmwf/ecbuild
        ecmwf/eckit
        ecmwf/odc
        ecmwf/eccodes
      dependency_branch: develop
      dependency_cmake_options: |
        ecmwf/eckit: "-G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DENABLE_TESTS=OFF  -DENABLE_ECKIT_SQL=OFF"
      cmake_options: "-G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DENABLE_LEGACY_IFSIO=ON ${{ matrix.cmake_options }}"
      ctest_options: "${{ matrix.ctest_options }}"