name: ci

on:
  # Trigger the workflow on push to master or develop, except tag creation
  push:
    branches:
      - 'master'
      - 'develop'
    tags-ignore:
      - '**'

  # Trigger the workflow on pull request
  pull_request: ~

  # Trigger the workflow manually
  workflow_dispatch: ~

  # Trigger after public PR approved for CI
  pull_request_target:
    types: [labeled]

jobs:
  build:
      runs-on: ubuntu-latest

      container:
        image: osgeo/gdal:ubuntu-small-latest

      steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python-gdal
      - name: Build
        run: |
          # Your build steps here

  ci:
    name: ci
    uses: ecmwf-actions/reusable-workflows/.github/workflows/ci-python.yml@v1
    with:
      codecov_upload: true
      notify_teams: false
      build_package_inputs: |
        self_build: false
